<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>TodayPlayStats</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PlayniteSDK" Version="6.15.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Playnite.SDK">
      <HintPath>$(PlayniteDir)\Playnite.SDK.dll</HintPath>
    </Reference>
    <Reference Include="PresentationFramework" />
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <None Update="extension.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>